import type { Board, BoardFrame, Project, Squad } from "@/models";
import { SCHEMA_VERSION } from "@/models";
import { createId } from "@/utils/id";

const createSampleSquad = (name: string, kit: Squad["kit"]): Squad => ({
  id: createId(),
  name,
  clubLogo: undefined,
  kit,
  players: [
    { id: createId(), name: "A. Berg", positionLabel: "GK", number: 1 },
    { id: createId(), name: "L. Holm", positionLabel: "LB", number: 3 },
    { id: createId(), name: "S. Lind", positionLabel: "CB", number: 4 },
    { id: createId(), name: "E. Nygaard", positionLabel: "CB", number: 5 },
    { id: createId(), name: "J. Karl", positionLabel: "RB", number: 2 },
    { id: createId(), name: "M. Olsen", positionLabel: "DM", number: 6 },
    { id: createId(), name: "K. Dahl", positionLabel: "CM", number: 8 },
    { id: createId(), name: "T. Storm", positionLabel: "AM", number: 10 },
    { id: createId(), name: "P. Jorg", positionLabel: "LW", number: 11 },
    { id: createId(), name: "I. Ahl", positionLabel: "RW", number: 7 },
    { id: createId(), name: "O. Soren", positionLabel: "ST", number: 9 },
  ],
});

const createFrame = (
  name: string,
  objects: BoardFrame["objects"] = []
): BoardFrame => ({
  id: createId(),
  name,
  objects,
  action: "",
  notes: "",
});

const createBoard = (
  name: string,
  objects: BoardFrame["objects"] = [],
  frames: BoardFrame[] = [createFrame("Frame 1", objects)],
  squadIds?: { homeSquadId?: string; awaySquadId?: string }
): Board => ({
  id: createId(),
  name,
  mode: frames.length > 1 ? "DYNAMIC" : "STATIC",
  pitchView: "FULL",
  pitchOverlay: "CORRIDORS",
  pitchOverlayText: true,
  notes: "Tryck pa en spelare for att redigera dess etikett.\n\nProva att spela upp animationen i dynamiskt lage.",
  notesTemplate: undefined,
  notesFields: {},
  homeSquadId: squadIds?.homeSquadId,
  awaySquadId: squadIds?.awaySquadId,
  playerLabel: {
    showName: true,
    showPosition: true,
    showNumber: false,
  },
  playerHighlights: [],
  playerLinks: [],
  layers: objects,
  frames,
  activeFrameIndex: 0,
});

export const createSampleProject = (): Project => {
  const homeSquad = createSampleSquad("Nordic FC", {
    shirt: "#e24a3b",
    shorts: "#0f1b1a",
    socks: "#f06d4f",
  });
  const awaySquad = createSampleSquad("City United", {
    shirt: "#2f6cf6",
    shorts: "#0f1b1a",
    socks: "#f2f1e9",
  });
  const ids = {
    homeGk: createId(),
    homeLb: createId(),
    homeCb: createId(),
    homeCm: createId(),
    homeSt: createId(),
    awayCb: createId(),
    awayDm: createId(),
    awayW: createId(),
    ball: createId(),
    arrow: createId(),
    cone1: createId(),
    cone2: createId(),
    goal: createId(),
    circle: createId(),
    rect: createId(),
    triangle: createId(),
    text: createId(),
  };

  const baseObjects: BoardFrame["objects"] = [
    {
      id: ids.homeGk,
      type: "player",
      position: { x: 14, y: 50 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#f9bf4a",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 3,
      locked: false,
      visible: true,
      squadPlayerId: homeSquad.players[0].id,
      hasBall: true,
      showName: true,
      showPosition: true,
      showNumber: false,
      tokenSize: 2.2,
    },
    {
      id: ids.homeLb,
      type: "player",
      position: { x: 22, y: 68 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#f9bf4a",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 3,
      locked: false,
      visible: true,
      squadPlayerId: homeSquad.players[1].id,
      showName: true,
      showPosition: true,
      showNumber: false,
      tokenSize: 2.1,
    },
    {
      id: ids.homeCb,
      type: "player",
      position: { x: 22, y: 38 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#f9bf4a",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 3,
      locked: false,
      visible: true,
      squadPlayerId: homeSquad.players[2].id,
      showName: true,
      showPosition: true,
      showNumber: false,
      tokenSize: 2.1,
    },
    {
      id: ids.homeCm,
      type: "player",
      position: { x: 38, y: 50 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#f9bf4a",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 3,
      locked: false,
      visible: true,
      squadPlayerId: homeSquad.players[7].id,
      showName: true,
      showPosition: true,
      showNumber: false,
      tokenSize: 2.1,
    },
    {
      id: ids.homeSt,
      type: "player",
      position: { x: 52, y: 50 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#f9bf4a",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 3,
      locked: false,
      visible: true,
      squadPlayerId: homeSquad.players[10].id,
      showName: true,
      showPosition: true,
      showNumber: false,
      tokenSize: 2.1,
    },
    {
      id: ids.awayCb,
      type: "player",
      position: { x: 70, y: 44 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#ffffff",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 3,
      locked: false,
      visible: true,
      squadPlayerId: awaySquad.players[2].id,
      showName: true,
      showPosition: true,
      showNumber: false,
      tokenSize: 2.1,
    },
    {
      id: ids.awayDm,
      type: "player",
      position: { x: 66, y: 56 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#ffffff",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 3,
      locked: false,
      visible: true,
      squadPlayerId: awaySquad.players[5].id,
      showName: true,
      showPosition: true,
      showNumber: false,
      tokenSize: 2.1,
    },
    {
      id: ids.awayW,
      type: "player",
      position: { x: 62, y: 30 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#ffffff",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 3,
      locked: false,
      visible: true,
      squadPlayerId: awaySquad.players[9].id,
      showName: true,
      showPosition: true,
      showNumber: false,
      tokenSize: 2.1,
    },
    {
      id: ids.ball,
      type: "ball",
      position: { x: 18, y: 52 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#111111",
        fill: "#ffffff",
        strokeWidth: 0.4,
        dash: [],
        opacity: 1,
      },
      zIndex: 4,
      locked: false,
      visible: true,
    },
    {
      id: ids.arrow,
      type: "arrow",
      position: { x: 22, y: 50 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#ffffff",
        fill: "rgba(255,255,255,0.1)",
        strokeWidth: 0.6,
        dash: [4, 3],
        opacity: 1,
      },
      zIndex: 1,
      locked: false,
      visible: true,
      points: [0, 0, 18, -8],
      head: true,
      dashed: true,
      curved: true,
      control: { x: 10, y: -10 },
    },
    {
      id: ids.cone1,
      type: "cone",
      position: { x: 34, y: 70 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#14211f",
        fill: "#f06d4f",
        strokeWidth: 0.3,
        dash: [],
        opacity: 1,
      },
      zIndex: 2,
      locked: false,
      visible: true,
      width: 6,
      height: 8,
    },
    {
      id: ids.cone2,
      type: "cone",
      position: { x: 46, y: 70 },
      rotation: 10,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#14211f",
        fill: "#f9bf4a",
        strokeWidth: 0.3,
        dash: [],
        opacity: 1,
      },
      zIndex: 2,
      locked: false,
      visible: true,
      width: 6,
      height: 8,
    },
    {
      id: ids.goal,
      type: "goal",
      position: { x: 86, y: 45 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#e6f0ee",
        fill: "rgba(230,240,238,0.08)",
        strokeWidth: 0.3,
        dash: [],
        opacity: 1,
      },
      zIndex: 1,
      locked: false,
      visible: true,
      width: 6,
      height: 6,
    },
    {
      id: ids.circle,
      type: "circle",
      position: { x: 42, y: 36 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#f2f1e9",
        fill: "rgba(255,255,255,0.05)",
        strokeWidth: 0.35,
        dash: [],
        opacity: 1,
      },
      zIndex: 0,
      locked: false,
      visible: true,
      radius: 6,
    },
    {
      id: ids.rect,
      type: "rect",
      position: { x: 58, y: 62 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#f2f1e9",
        fill: "rgba(255,255,255,0.05)",
        strokeWidth: 0.35,
        dash: [6, 4],
        opacity: 1,
      },
      zIndex: 0,
      locked: false,
      visible: true,
      width: 12,
      height: 8,
      cornerRadius: 1.2,
    },
    {
      id: ids.triangle,
      type: "triangle",
      position: { x: 62, y: 22 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#f2f1e9",
        fill: "rgba(255,255,255,0.08)",
        strokeWidth: 0.35,
        dash: [],
        opacity: 1,
      },
      zIndex: 0,
      locked: false,
      visible: true,
      width: 8,
      height: 7,
    },
    {
      id: ids.text,
      type: "text",
      position: { x: 36, y: 20 },
      rotation: 0,
      scale: { x: 1, y: 1 },
      style: {
        stroke: "#0f1b1a",
        fill: "#e6f0ee",
        strokeWidth: 0,
        dash: [],
        opacity: 1,
      },
      zIndex: 2,
      locked: false,
      visible: true,
      text: "Press trigger\nLW jumps",
      fontSize: 2.2,
      bold: true,
      background: true,
      align: "center",
      width: 18,
      height: 8,
    },
  ];

  const moveFrame = (
    objects: BoardFrame["objects"],
    updates: Record<string, { x: number; y: number }>
  ) =>
    objects.map((object) =>
      updates[object.id]
        ? { ...object, position: updates[object.id] }
        : object
    );

  const frame2Objects = moveFrame(baseObjects, {
    [ids.homeCm]: { x: 42, y: 50 },
    [ids.homeSt]: { x: 58, y: 52 },
    [ids.awayDm]: { x: 64, y: 54 },
    [ids.awayW]: { x: 64, y: 32 },
    [ids.ball]: { x: 30, y: 52 },
  });

  const frame3Objects = moveFrame(baseObjects, {
    [ids.homeCm]: { x: 46, y: 48 },
    [ids.homeSt]: { x: 62, y: 54 },
    [ids.awayCb]: { x: 72, y: 46 },
    [ids.awayDm]: { x: 66, y: 56 },
    [ids.ball]: { x: 42, y: 50 },
  });

  const frames = [
    createFrame("Frame 1", baseObjects),
    { ...createFrame("Frame 2", frame2Objects), action: "Pass" },
    { ...createFrame("Frame 3", frame3Objects), action: "Through ball" },
  ];

  const board = createBoard(
    "Pressing Setup",
    baseObjects,
    frames,
    { homeSquadId: homeSquad.id, awaySquadId: awaySquad.id }
  );
  return {
    id: createId(),
    name: "Demo: High Press",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    schemaVersion: SCHEMA_VERSION,
    isSample: true,
    settings: {
      homeKit: { ...homeSquad.kit },
      awayKit: { ...awaySquad.kit },
      attachBallToPlayer: false,
    },
    boards: [board],
    squads: [homeSquad, awaySquad],
    activeBoardId: board.id,
  };
};
